Exception: STATUS_ACCESS_VIOLATION at rip=001801674DD
rax=0000000000000000 rbx=00000005D67F246F rcx=0000000000000000
rdx=0000000000000000 rsi=0000000566DD2DA0 rdi=000000000000002B
r8 =0000000000234AF8 r9 =0000000000000073 r10=000006FFFEFCE6F0
r11=000000000000006D r12=000006FFFF038C38 r13=0000000000234AF0
r14=00000005D67F2455 r15=0000000000000000
rbp=0000000566DBD778 rsp=0000000000234948
program=C:\cygwin64\bin\python3.2m.exe, pid 2064, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00566DBD778  001801674DD (00000000000, 6FFFF22AF10, 00566CAA91C, 00000000000)
00566DBD778  00566CCFBBD (00566D0F0F8, 00000234B00, 00566CA57C6, 6FFFEFDF9D0)
6FFFEFE73B0  00566D0AF55 (00000234CD8, 6FFFEFECB08, 00000000000, 00000234B60)
6FFFEFE73B0  005D67E39DE (00000000000, 005D67F216A, 00566CC74DE, 6FFFFFB7140)
00566D884A0  00566CBE307 (00600550C00, 6FFFF22CAE8, 0060043CE40, 6FFFFFB1180)
00566D884A0  00566C7A0D9 (000000001D0, 0060002D520, 0060055A2D0, 0060042FD50)
00600010AA0  00566CFE73F (000000001E0, 0060002D520, 0060055A5E0, 0060042FD50)
00600010AA0  00566D01966 (7FF9DDF8D93E, 00000000002, 00566D7B6D0, 00000000001)
00000000000  00566D0218E (00566CC780B, 6FFFEFD9248, 6FFFF1B1160, 00000000002)
6FFFEFD95F0  00566C9B6A2 (6FFFF1B1160, 00566D884A0, 6FFFF0AEF18, 000002351B0)
00566D884A0  00566C7A0D9 (1A247BA930E6B3ED, 00000000002, 00566D80EA0, 00600454130)
6FFFEFDF990  00566C8BC3A (00000000001, 000002352C8, 00566C7702B, 6FFFEFEF768)
00566D884A0  00566C7A0D9 (00566CC74DE, 00566D727C0, 00566D727C0, 00000000000)
00000000000  00566C7A692 (6FFFEFE5FB8, 00000000000, 6FFFEFDF990, 6FFFEFDF990)
00000000000  00566CBB28E (006005506B0, 6FFFFF46ED8, 68444B913699B3A6, 00600010AA0)
00000000000  00566CC164A (6FFFEF11848, 6FFFEFDF990, 00600542BE1, 000002353A0)
End of stack trace (more stack frames may be present)
